package model;

/**
 * Created by Oscar on 12-10-2015.
 */
public class User {


    //defining variables

    private int id;
    private String firstName;
    private String lastName;
    private String userName;
    private String password;
    private String created;
    private String Status;

    //autogenerated getters and setters

    public int getId() {
        return id;
    }

      public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCreated() {
        return created;
    }

    public void setCreated(String created) {
        this.created = created;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String status) {
        Status = status;
    }





//end of User calls
}
